name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Run Docker Container
        run: |
          docker build -t your-image-name:your-tag .
          docker run -d --name your-container-name -p 80:80 your-image-name:your-tag
        working-directory: ./
