name: Build and Run Docker Container
on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ./ # Specify the path to your Dockerfile directory
      - name: Build and Run Docker Container
        run: |
          docker build -t kreativnoime : kreativno.
          docker run -d --name kreativnoime -p 80:80 kreativnoime:kreativno
        working-directory: ./ # Specify the path to your Dockerfile directory
