name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Remove Old Docker Image
        #run: |
          #ssh user@your-server-ip "docker stop your-container-name || true"
          #ssh user@your-server-ip "docker rm your-container-name || true"
          #ssh user@your-server-ip "docker rmi your-image-name:your-tag || true"
        #env:
          #SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t your-image-name:your-tag .
        working-directory: path/to/your/dockerfile
      - name: Copy Docker Image to Server
        run: |
          scp your-image-name:your-tag user@your-server-ip:/path/on/server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - name: SSH into Server and Deploy
        run: |
          ssh user@your-server-ip "docker run -d --name your-container-name -p 80:80 your-image-name:your-tag"
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
