name: Build react

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build Docker Image
      run: docker build -t my-react-app .
      working-directory: ./path/to/your/Dockerfile-directory

    - name: Run Docker Container
      run: docker run -d -p 80:80 my-react-app
